### ISSUE TITLE
libgd-dev required.

### ISSUE THREAD

**Issue by hsie** [VirtuBox/plesk-nginx#1]
Thanks for this while when I try to install, I was told that error message below, just wonder how to fix, thanks in advance!

The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgd-dev : Depends: libtiff-dev
E: Unable to correct problems, you have held broken packages.

**Comment by VirtuBox** [comment]
Hello @hsie,

have you tried  ?
```
apt-get install -f 
```

**Comment by hsie** [comment]
thanks and the problem solved, but new one appears, below is the error message.

Unit sw-nginx.service does not exist, proceeding anyway.
nginx.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nginx
E: Unable to locate package sw-nginx
E: No packages found

**Comment by VirtuBox** [comment]
What is your linux distribution and Plesk release ?
